#! /usr/bin/env bash

# Generate Swift configuration files for SGE with manually-started Swift workers (passive coasters)

cat >tc <<END
sge       bash      /bin/bash null null ENV::PATH="$PATH";GLOBUS::maxwalltime="00:01:00"
END

# FIXME: examine effect of 1-min default maxwalltime above

cat >sites.xml <<END
<config>

  <pool handle="sge">
    <execution provider="coaster" url="none" jobmanager="local:NA"/>
    <profile namespace="globus" key="workerManager">passive</profile>
    <!-- <profile namespace="globus" key="workersPerNode">$cores</profile> -->
    <profile namespace="globus" key="workersPerNode">1</profile>
    <profile namespace="karajan" key="jobThrottle">$throttle</profile>
    <profile namespace="karajan" key="initialScore">10000</profile>
    <filesystem provider="local" url="none"/>
    <workdirectory>$(pwd)/swiftwork</workdirectory>
    <scratch>$pwd/swiftscratch</scratch>
    <profile namespace="swift" key="stagingMethod">proxy</profile>
  </pool>

</config>
END

# Note abve: workdirectory for cluster must be on shared filesystem

cat >cf <<END
wrapperlog.always.transfer=false
sitedir.keep=false
execution.retries=$num_retries
lazy.errors=false
status.mode=provider
use.provider.staging=true
provider.staging.pin.swiftfiles=true
#throttle.host.submit=1
END

