#! /usr/bin/env bash

throttleOneCore="0.00"  # FIXME: test if new swft fix makes zero OK rather than -0.001

if [ -r /proc/cpuinfo ]; then
  localcores=$(grep '^processor' /proc/cpuinfo | wc -l)
else
  localcores=1
fi

if [ $cores -eq 0 ]; then
  cores=$localcores
fi

cat >tc <<END
fork bashlocal /bin/bash null null null
END

cat >sites.xml <<END
<config>
  <pool handle="fork">
    <execution provider="local" url="none" />
    <profile key="jobThrottle" namespace="karajan">0.15</profile>
    <profile namespace="karajan" key="initialScore">10000</profile>
    <filesystem provider="local" url="none" />
    <profile namespace="env" key="LD_LIBRARY_PATH">$LD_LIBRARY_PATH</profile>
    <profile namespace="env" key="R_LIBS_USER">$R_LIBS_USER</profile>
    <workdirectory>$(pwd)/swiftwork</workdirectory>
  </pool>
END

for i in `$SEQ 0 $((cores-1))`; do

# FIXME: how to get the right PATH for R in here?
# use /bin/sh and count on users PATH?
# then add ENV::PATH as an option, e.g., from options(swift.remotepath and swift.remotepath.sitename)

cat >>tc <<END
local${i} bash /bin/bash null null ENV::SWIFTR_TMP="$SWIFTR_TMP";ENV::PATH="$PATH";ENV::SWIFT_JOB_SLOT="${i}";ENV::SWIFT_WORKER_PID="$$"
END

cat >>sites.xml <<END
  <pool handle="local${i}">
    <execution provider="local" url="none" />
    <profile key="jobThrottle" namespace="karajan">$throttleOneCore</profile>
    <profile namespace="karajan" key="initialScore">10000</profile>
    <profile namespace="env" key="LD_LIBRARY_PATH">$LD_LIBRARY_PATH</profile>
    <profile namespace="env" key="R_LIBS_USER">$R_LIBS_USER</profile>
    <filesystem provider="local" url="none" />
    <workdirectory>$(pwd)/swiftwork</workdirectory>
  </pool>
END

done

echo '</config>' >>sites.xml

cat >cf <<END
wrapperlog.always.transfer=false
sitedir.keep=false
execution.retries=$num_retries
lazy.errors=false
status.mode=provider
use.provider.staging=false
provider.staging.pin.swiftfiles=false
throttle.host.submit=1
END


